### ISSUE TITLE
Proposal to change color prop name from timeline-item-base component.

### ISSUE THREAD

**Issue by delete** [luyilin/vue-cute-timeline#6]
Hi,

First, awesome work @luyilin !

I was trying to change the title font color, but I found that the **color** prop change the background, not the font color.

What do you thing about change the prop name(something like bgColor), and create a font prop color?

https://github.com/luyilin/vue-cute-timeline/blob/master/src/timelineItemBase.vue#L6

**Comment by luyilin** [comment]
😊Thanks for your nice suggestion, I will add a prop named fontColor and change the color to bgColor. 
And PR is welcomed~

**Comment by luyilin** [comment]
I just add a `font-color` prop to set the font color of the timeline item and title, and change the `color` prop to `bg-color` to make a difference.
After I add the prop I found actually you can set the font color without it. Because the content of the timeline item and title is a slot. You can set custom style of it like this:
```
<timeline>
    <timeline-title>
		<p style="color: red">title<p>
	</timeline-title>
</timeline>
```
Maybe the `font-color` prop is not necessary. I'm considering remove it, as the old code has met the need. Sorry to add code without thinking too much, what do you think about it?

**Comment by delete** [comment]
Thanks for the effort! :+1: 

What do you thing about let these options already implemented, and if the user want more custom things, then they use the slots?

**Comment by luyilin** [comment]
Okay, I will keep the feature. I mean maybe the component should focus on the timeline, only include the circle and the line. The content of it will be more flexible as a slot instead of a series of props. But props are more easily to be understand and used, so I will keep it though. Thanks for your suggestion~
